export const GET_HOME_REQUEST = 'GET_HOME_REQUEST'
export const GET_HOME_SUCCESS = 'GET_HOME_SUCCESS'
export const GET_HOME_ERROR = 'GET_HOME_ERROR'

export const SEND_SIGNIN_REQUEST = 'SEND_SIGNIN_REQUEST'
export const SEND_SIGNIN_SUCCESS = 'SEND_SIGNIN_SUCCESS'
export const SEND_SIGNIN_ERROR = 'SEND_SIGNIN_ERROR'

export const SEND_SIGNINOTP_REQUEST = 'SEND_SIGNINOTP_REQUEST'
export const SEND_SIGNINOTP_SUCCESS = 'SEND_SIGNINOTP_SUCCESS'
export const SEND_SIGNINOTP_ERROR = 'SEND_SIGNINOTP_ERROR'

export const SEND_SIGNUP_REQUEST = 'SEND_SIGNUP_REQUEST'
export const SEND_SIGNUP_SUCCESS = 'SEND_SIGNUP_SUCCESS'
export const SEND_SIGNUP_ERROR = 'SEND_SIGNUP_ERROR'

export const SEND_SIGNUPOTP_REQUEST = 'SEND_SIGNUPOTP_REQUEST'
export const SEND_SIGNUPOTP_SUCCESS = 'SEND_SIGNUPOTP_SUCCESS'
export const SEND_SIGNUPOTP_ERROR = 'SEND_SIGNUPOTP_ERROR'

export const SEND_ACCOUNT_CREATE_REQUEST = 'SEND_ACCOUNT_CREATE_REQUEST'
export const SEND_ACCOUNT_CREATE_SUCCESS = 'SEND_ACCOUNT_CREATE_SUCCESS'
export const SEND_ACCOUNT_CREATE_ERROR = 'SEND_ACCOUNT_CREATE_ERROR'

export const SEND_SOCIAL_REQUEST = 'SEND_SOCIAL_REQUEST'
export const SEND_SOCIAL_SUCCESS = 'SEND_SOCIAL_SUCCESS'
export const SEND_SOCIAL_ERROR = 'SEND_SOCIAL_ERROR'

export const UPDATE_NAME_REQUEST = 'UPDATE_NAME_REQUEST'
export const UPDATE_NAME_SUCCESS = 'UPDATE_NAME_SUCCESS'
export const UPDATE_NAME_ERROR = 'UPDATE_NAME_ERROR'

export const UPDATE_MOBILE_REQUEST = 'UPDATE_MOBILE_REQUEST'
export const UPDATE_MOBILE_SUCCESS = 'UPDATE_MOBILE_SUCCESS'
export const UPDATE_MOBILE_ERROR = 'UPDATE_MOBILE_ERROR'

export const UPDATE_MOBILE_VERIFY_REQUEST = 'UPDATE_MOBILE_VERIFY_REQUEST'
export const UPDATE_MOBILE_VERIFY_SUCCESS = 'UPDATE_MOBILE_VERIFY_SUCCESS'
export const UPDATE_MOBILE_VERIFY_ERROR = 'UPDATE_MOBILE_VERIFY_ERROR'

export const GET_TRANSLATION_REQUEST = 'GET_TRANSLATION_REQUEST'
export const GET_TRANSLATION_SUCCESS = 'GET_TRANSLATION_SUCCESS'
export const GET_TRANSLATION_ERROR = 'GET_TRANSLATION_ERROR'

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR'

export const GET_FILTER_TYPE_REQUEST = 'GET_FILTER_TYPE_REQUEST'
export const GET_FILTER_TYPE_SUCCESS = 'GET_FILTER_TYPE_SUCCESS'
export const GET_FILTER_TYPE_ERROR = 'GET_FILTER_TYPE_ERROR'

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'

export const GET_PRODUCT_SEARCH_REQUEST = 'GET_PRODUCT_SEARCH_REQUEST'
export const GET_PRODUCT_SEARCH_SUCCESS = 'GET_PRODUCT_SEARCH_SUCCESS'
export const GET_PRODUCT_SEARCH_ERROR = 'GET_PRODUCT_SEARCH_ERROR'

export const GET_PRODUCT_PROMOTION_REQUEST = 'GET_PRODUCT_PROMOTION_REQUEST'
export const GET_PRODUCT_PROMOTION_SUCCESS = 'GET_PRODUCT_PROMOTION_SUCCESS'
export const GET_PRODUCT_PROMOTION_ERROR = 'GET_PRODUCT_PROMOTION_ERROR'

export const GET_PRODUCT_CUSTOM_REQUEST = 'GET_PRODUCT_CUSTOM_REQUEST'
export const GET_PRODUCT_CUSTOM_SUCCESS = 'GET_PRODUCT_CUSTOM_SUCCESS'
export const GET_PRODUCT_CUSTOM_ERROR = 'GET_PRODUCT_CUSTOM_ERROR'

export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_DETAIL_REQUEST'
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS'
export const GET_PRODUCT_DETAIL_ERROR = 'GET_PRODUCT_DETAIL_ERROR'

export const GET_RELATED_PRODUCT_REQUEST = 'GET_RELATED_PRODUCT_REQUEST'
export const GET_RELATED_PRODUCT_SUCCESS = 'GET_RELATED_PRODUCT_SUCCESS'
export const GET_RELATED_PRODUCT_ERROR = 'GET_RELATED_PRODUCT_ERROR'

export const GET_FEATURE_PRODUCT_REQUEST = 'GET_FEATURE_PRODUCT_REQUEST'
export const GET_FEATURE_PRODUCT_SUCCESS = 'GET_FEATURE_PRODUCT_SUCCESS'
export const GET_FEATURE_PRODUCT_ERROR = 'GET_FEATURE_PRODUCT_ERROR'

export const GET_PROMO_FEATURE_PRODUCT_REQUEST = 'GET_PROMO_FEATURE_PRODUCT_REQUEST'
export const GET_PROMO_FEATURE_PRODUCT_SUCCESS = 'GET_PROMO_FEATURE_PRODUCT_SUCCESS'
export const GET_PROMO_FEATURE_PRODUCT_ERROR = 'GET_PROMO_FEATURE_PRODUCT_ERROR'

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST'
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS'
export const GET_ACCOUNT_ERROR = 'GET_ACCOUNT_ERROR'

// COUPON type
export const COLLECT_COUPON_REQUEST = 'COLLECT_COUPON_REQUEST'
export const COLLECT_COUPON_SUCCESS = 'COLLECT_COUPON_SUCCESS'
export const COLLECT_COUPON_ERROR = 'COLLECT_COUPON_ERROR'

export const GET_COUPON_LIST_REQUEST = 'GET_COUPON_LIST_REQUEST'
export const GET_COUPON_LIST_SUCCESS = 'GET_COUPON_LIST_SUCCESS'
export const GET_COUPON_LIST_ERROR = 'GET_COUPON_LIST_ERROR'

export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST'
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS'
export const APPLY_COUPON_ERROR = 'APPLY_COUPON_ERROR'

export const CANCEL_COUPON_REQUEST = 'CANCEL_COUPON_REQUEST'
export const CANCEL_COUPON_SUCCESS = 'CANCEL_COUPON_SUCCESS'
export const CANCEL_COUPON_ERROR = 'CANCEL_COUPON_ERROR'

// Ecommerce type
export const CREATE_QUOTE_REQUEST = 'CREATE_QUOTE_REQUEST'
export const CREATE_QUOTE_SUCCESS = 'CREATE_QUOTE_SUCCESS'
export const CREATE_QUOTE_ERROR = 'CREATE_QUOTE_ERROR'

export const CREATE_CART_REQUEST = 'CREATE_CART_REQUEST'
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS'
export const CREATE_CART_ERROR = 'CREATE_CART_ERROR'

export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_ERROR = 'GET_CART_ERROR'

export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const UPDATE_CART_ERROR = 'UPDATE_CART_ERROR'

export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST'
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS'
export const DELETE_CART_ERROR = 'DELETE_CART_ERROR'

export const GET_TOWNSHIP_REQUEST = 'GET_TOWNSHIP_REQUEST'
export const GET_TOWNSHIP_SUCCESS = 'GET_TOWNSHIP_SUCCESS'
export const GET_TOWNSHIP_ERROR = 'GET_TOWNSHIP_ERROR'

export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_ERROR = 'CREATE_ADDRESS_ERROR'

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_ERROR = 'DELETE_ADDRESS_ERROR'

export const EST_SHIPPING_METHOD_REQUEST = 'EST_SHIPPING_METHOD_REQUEST'
export const EST_SHIPPING_METHOD_SUCCESS = 'EST_SHIPPING_METHOD_SUCCESS'
export const EST_SHIPPING_METHOD_ERROR = 'EST_SHIPPING_METHOD_ERROR'

export const SET_SHIPPING_METHOD_REQUEST = 'SET_SHIPPING_METHOD_REQUEST'
export const SET_SHIPPING_METHOD_SUCCESS = 'SET_SHIPPING_METHOD_SUCCESS'
export const SET_SHIPPING_METHOD_ERROR = 'SET_SHIPPING_METHOD_ERROR'

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR'

// ORDER
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'

export const GET_ORDER_DETAIL_REQUEST = 'GET_ORDER_DETAIL_REQUEST'
export const GET_ORDER_DETAIL_ERROR = 'GET_ORDER_DETAIL_ERROR'
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS'

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST'
export const CANCEL_ORDER_ERROR = 'CANCEL_ORDER_ERROR'
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS'